---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      # Might make sense once everything is at Python 3
      # - id: check-ast
      - id: check-added-large-files
        args:
          - '--maxkb=1024'
      - id: debug-statements
      - id: mixed-line-ending
        args:
          - '--fix=no'
      - id: check-docstring-first
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: 'https://github.com/psf/black'
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: 'https://github.com/myint/autoflake'
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - '--in-place'
          - '--recursive'
          - '--remove-all-unused-imports'
          - '--expand-star-imports'
          - '--ignore-init-module-imports'
          - '--remove-unused-variables'
  - repo: 'https://github.com/myint/docformatter'
    rev: v1.4
    hooks:
      - id: docformatter
        args:
          - '--in-place'
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.5.1
    hooks:
      - id: pip-compile
        files: ^requirements\.in$
