[project]
name = "gbt_rfi_gui"
version = "1.1"
description = "GBT RFI GUI"
readme = "README.md"
authors = [
    { name = "Kathlyn Purcell", email = "kpurcell@nrao.edu" }
]
requires-python = ">=3.11"
dependencies = [
    "django-crispy-forms<2",
    "django-debug-toolbar",
    "django-environ",
    "django-extensions<3",
    "Django<4",
    "ipdb",
    "ipython",
    "matplotlib",
    "mysqlclient",
    "pandas",
    "pip-tools",
    "plotly",
    "psycopg2-binary",
    "PyQt5",
    "scipy",
]
url = "https://pypi.org/project/gbt-rfi-gui/"

[project.scripts]
gbt-rfi-gui = "gbt_rfi_gui.gbt_rfi_gui:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool]

[tool.isort]
# See: https://pycqa.github.io/isort/docs/configuration/options/#example-pyprojecttoml
profile = "black"
combine_as_imports = true
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "DJANGO",
    "DJANGOLIBS",
    "FIRSTPARTY",
    "LOCALFOLDER"
]
# Group for all django imports
known_django = ["django"]
# Group for all django-related packages
known_djangolibs = [
    "dal",
    "dal_select2",
    "django_cas_ng",
    "django_crispy_forms",
    "django_debug_toolbar",
    "django_environ",
    "django_extensions",
    "django_filters",
    "django_tables2",
    "django_stronghold",
]
